In [2]:
import numpy as np
lst=np.array(["margery","khaleesi","cersei","jonsnow"])
print(lst[1])

khaleesi


In [3]:
import numpy as np
lst=np.array(["margery","khaleesi","cersei","jonsnow"])
print(lst[1])
print(lst[3])

khaleesi
jonsnow


In [14]:
import numpy as np
num=np.array([1,6,7,8,4,4,6,2,6,8])
print(num[[1,5]])

[6 4]


In [8]:
import numpy as np
lst=np.array([["margery","khaleesi"],["cersei","jonsnow"]])
print(lst[0])
print(lst[1])

['margery' 'khaleesi']
['cersei' 'jonsnow']


In [15]:
import numpy as np
arr=np.array([6,4,3,7,3,80])
print(arr[arr>25])

[80]


In [18]:
marks=np.array([34,34,65,78,31,89])
print(marks[marks>45])

[65 78 89]


In [21]:
arr=np.array([6,4,3,7,3,80])
for i in range(6,80):
    print(i)

6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79


In [22]:
for i in([5,54,65,67,89]):
    print(i)

5
54
65
67
89


In [23]:
arr=np.array([45,76,84,787,53])
for i in arr:
    print(i)

45
76
84
787
53


In [25]:
arr=np.array([[7,6,5,3,7],[5,6,7,8,99]])
print(arr)

[[ 7  6  5  3  7]
 [ 5  6  7  8 99]]


In [31]:
arr=np.array([["d","h","u"],["v","i","t"],["h","a","c"]])
print(arr)

[['d' 'h' 'u']
 ['v' 'i' 't']
 ['h' 'a' 'c']]


In [32]:
arr=np.array([[34,65],[78,98],[56,78]])
for row in arr:
    print(row)

[34 65]
[78 98]
[56 78]


In [35]:
for i in np.nditer(arr):
    print(i)


34
65
78
98
56
78


In [38]:
num=([5,6,7,8,9,2])
for i in np.nditer(num):
    print(i)

(array(5), array(6), array(7), array(8), array(9), array(2))


In [39]:
arr1=([2,3,4])
arr2=([5,6,7])
print(arr1+arr2)

[2, 3, 4, 5, 6, 7]


In [40]:
arr1=(["cup"])
arr2=(["cake"])
print(arr1+arr2)

['cup', 'cake']
