In [3]:
import numpy as np
num1=([7,8,9,10])
num2=([1,2,3,4])
num3=np.concatenate((num1,num2))
print(num3)

[ 7  8  9 10  1  2  3  4]


In [4]:
arr=np.array([2,4,6,8])
arr1=np.where(arr==6)
print(arr1)

(array([2]),)


In [8]:
arr=np.array([2,4,6,8])
arr1=np.sort(arr)
print(arr1)

[2 4 6 8]


In [2]:
import numpy as np
marks=np.array([89,56,45,34,32])
print(marks[marks>=45])

[89 56 45]


In [3]:
marks=np.sum([30,60,66,99,100])
print(marks)

355


In [4]:
marks=np.average([77,45,67,88,90])
print(marks)

73.4


In [6]:
marks1=np.min([23,45,56,67,89])
marks2=np.max([34,56,78,89,90])
print(marks1)
print(marks2)



23
90


In [9]:
arr=np.array([40,60,70,100,700])
print(np.power(arr,5))



[      102400000       777600000      1680700000     10000000000
 168070000000000]
