In [4]:
import numpy as np 
a=np.array([1,2,3])
b=np.array([5,6,7])
print(np.vstack((a,b)))

[[1 2 3]
 [5 6 7]]


In [6]:
import numpy as np 
a=np.array([12,24,56])
b=np.array([5,67,89])
print(np.hstack((a,b)))

[12 24 56  5 67 89]


In [9]:
arr=np.array([2,3,4,5])
print(arr+10)

[12 13 14 15]


In [10]:
arr=np.array([70,65,55,100])
print(arr-10)

[60 55 45 90]


In [11]:
arr=np.array([[2,3,4],[4,5,8]])
print(arr+[5,10,3])

[[ 7 13  7]
 [ 9 15 11]]
