In [4]:
import numpy as np 
a=np.array([1,2,3])
b=np.array([5,6,7])
print(np.vstack((a,b)))

[[1 2 3]
 [5 6 7]]


In [6]:
import numpy as np 
a=np.array([12,24,56])
b=np.array([5,67,89])
print(np.hstack((a,b)))

[12 24 56  5 67 89]
